/** Compact EOD fields useful for long-series bond/equity analysis. */
export const HISTORY_FIELDS = [
  "SECID",
  "BOARDID",
  "TRADEDATE",
  "SHORTNAME",
  "NUMTRADES",
  "VOLUME",
  "VALUE",
  "OPEN",
  "LOW",
  "HIGH",
  "CLOSE",
  "LEGALCLOSEPRICE",
  "WAPRICE",
  "YIELDCLOSE",
  "YIELDCLOSE_QC",
  "YIELDATWAP",
  "YIELDTOOFFER",
  "DURATION",
  "ACCINT",
  "COUPONPERCENT",
  "COUPONVALUE",
  "FACEVALUE",
  "MATDATE",
  "OFFERDATE",
  "BUYBACKDATE",
  "ZSPREAD",
  "ZSPREADATWAPRICE",
  "CURRENCYID",
  "qc_flags",
] as const;
